### ISSUE TITLE
maintaining the official xml syntax file

### ISSUE THREAD

**Issue by chrisbra** [amadeus/vim-xml#1]
Hi amadeus,
I have been [asked to also maintain the xml syntax](https://github.com/chrisbra/vim-xml-ftplugin/issues/15) files. in my https://github.com/chrisbra/vim-xml-ftplugin/ repository. However I did not know you are already maintaining your own version here. You already have fixed some bugs here and if you like to maintain the official vim xml syntax file, I am fine with that. If not, I'll keep on maintaining it. In the later case, please feel free to open a PR fixing any issues you have noticed. Thanks!

See also https://github.com/chrisbra/vim-xml-ftplugin/pull/16#issuecomment-533974426

**Comment by amadeus** [comment]
Hey @chrisbra! 

Thanks for the note! I've responded more in https://github.com/chrisbra/vim-xml-ftplugin/pull/16
